"""Centralized combat tuning values for the player sandbox."""

ROLL_COOLDOWN = 1.0
ROLL_DISTANCE = 70.0
ROLL_DURATION = 0.30
PLAYER_ATTACK_DURATION = 0.24
PLAYER_ATTACK_COOLDOWN = 0.36
ENEMY_ATTACK_DURATION = 0.24
ENEMY_ATTACK_INTERVAL = 1.0

# These values are reserved for the next stamina/parry batches.
MAX_STAMINA = 3.0
STAMINA_REGEN_RATE = 0.35
BLOCK_STAMINA_COST = 1.0
PARRY_STAMINA_REWARD = 1.0
PARRY_WINDOW = 0.12
PARRY_STUN_DURATION = 1.25
GUARD_BREAK_DAMAGE_MULTIPLIER = 1.5
GUARD_BREAK_DURATION = 0.9
GUARD_BREAK_RECOVERY_THRESHOLD = 0.10
GUARD_BREAK_FLASH_DURATION = 0.18
GUARD_BREAK_SPRITE_DURATION = 1.0

STATE_IDLE = "IDLE"
STATE_ATTACKING = "ATTACKING"
STATE_BLOCKING = "BLOCKING"
STATE_ROLLING = "ROLLING"
STATE_PARRIED = "PARRIED"
STATE_GUARD_BROKEN = "GUARD_BROKEN"
STATE_STUNNED = "STUNNED"
